spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://switchyard.proxy.rlwy.net:56533/railway
    username: postgres
    password: sTcnwTlQcJMELANtyaBVYUWONyZOXRhp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
 
server:
  port: 8080